# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'SharedCode', :path => '/Users/vchechin/Projects/diary/SharedCode'

end
